pipeline {
    agent any
    
    tools {
        nodejs 'node22'
    }
    
    environment {
        SONARQUBE_SCANNER= tool 'sonar-scanner'
    }
    
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/iam-aniket-dutta/DevSecOps_Project_3Tier_App.git'
            }
        }
        
        stage('Install dependancies(npm pacakges)') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('Unit Tests') {
            steps {
                sh 'npm test'
            }
        }
        
        stage('Trivy File Sytem Scan') {
            steps {
                sh 'trivy fs --format table -o fs-report.html .'
            }
        }
        
        stage('Sonar Qube Scan') {
            steps {
                withSonarQubeEnv('sonarqube-server') {
                    sh ' $SONARQUBE_SCANNER/bin/sonar-scanner -Dsonar.projectKey=Campground -Dsonar.projectName=Campground'
                }
            }
        }
        
        stage('Docker build image') {
            steps {
               script{
                   withDockerRegistry(credentialsId: 'docker-credentials', toolName: 'docker') {
                        sh 'docker build -t aniketnitu2026/3tier-app:latest .'
                    }
               }
            }
        }
        
        stage('Trivy Docak Image Scan') {
            steps {
                sh 'trivy image --format table -o image-report.html aniketnitu2026/3tier-app:latest'
            }
        }
        
        stage('Docker Push image') {
            steps {
               script{
                   withDockerRegistry(credentialsId: 'docker-credentials', toolName: 'docker') {
                        sh 'docker push aniketnitu2026/3tier-app:latest'
                    }
               }
            }
        }
        
        stage('Docker Deployment') {
        steps {
            script {
                withCredentials([file(credentialsId: 'app-env', variable: 'DOTENV_FILE')]) {
                    withDockerRegistry(credentialsId: 'docker-credentials', toolName: 'docker') {
                        // 2. Stop and remove any existing container to prevent port conflicts
                        sh 'docker rm -f 3tier-app-dev || true'
                        // 3. Run the new container using the --env-file flag
                        // The variable ${DOTENV_FILE} points to the temporary path where Jenkins stored your secret
                        sh 'docker run -d  -p 3000:3000 --name 3tier-app-dev --env-file ${DOTENV_FILE} aniketnitu2026/3tier-app:latest'
                    }
                }
            }
        }
}
    }
}
