pipeline {
    agent any
    
    tools {
        nodejs 'node22'
    }
    
    environment {
        SONARQUBE_SCANNER= tool 'sonar-scanner'
    }
    
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/iam-aniket-dutta/DevSecOps_Project_3Tier_App.git'
            }
        }
        
        stage('Install dependancies(npm pacakges)') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('Unit Tests') {
            steps {
                sh 'npm test'
            }
        }
        
        stage('Trivy File Sytem Scan') {
            steps {
                sh 'trivy fs --format table -o fs-report.html .'
            }
        }
        
        stage('Sonar Qube Scan') {
            steps {
                withSonarQubeEnv('sonarqube-server') {
                    sh ' $SONARQUBE_SCANNER/bin/sonar-scanner -Dsonar.projectKey=Campground -Dsonar.projectName=Campground'
                }
            }
        }
        
        stage('Docker build image') {
            steps {
               script{
                   withDockerRegistry(credentialsId: 'docker-credentials', toolName: 'docker') {
                        sh 'docker build -t aniketnitu2026/3tier-app:latest .'
                    }
               }
            }
        }
        
        stage('Trivy Docak Image Scan') {
            steps {
                sh 'trivy image --format table -o image-report.html aniketnitu2026/3tier-app:latest'
            }
        }
        
        stage('Docker Push image') {
            steps {
               script{
                   withDockerRegistry(credentialsId: 'docker-credentials', toolName: 'docker') {
                        sh 'docker push aniketnitu2026/3tier-app:latest'
                    }
               }
            }
        }

        stage('List file structure') {
            steps {
                sh 'ls -ltr'
            }
        }

        stage('Deploy to EKS') {
            steps {
                script {
                    withKubeCredentials(kubectlCredentials: [[
                        caCertificate: '', 
                        clusterName: ' camp-cluster', 
                        contextName: '', 
                        credentialsId: 'k8-service-account-token', 
                        namespace: 'webapps', 
                        serverUrl: 'https://E5F18354D7B632FF2E865A0E7F4F1E2A.gr7.us-east-1.eks.amazonaws.com'
                    ]]) {
                        sh 'kubectl apply -f env-secret.yml'
                        sh 'sleep 30'
                        sh 'kubectl apply -f deploy.yml'
                        sh 'sleep 30'
                        sh 'kubectl apply -f svc.yml'
                        sh 'sleep 30'
                    }
                }
            }
        }

        stage('Verify the EKS Deploy') {
            steps {
                script {
                    withKubeCredentials(kubectlCredentials: [[
                        caCertificate: '', 
                        clusterName: ' camp-cluster', 
                        contextName: '', 
                        credentialsId: 'k8-service-account-token', 
                        namespace: 'webapps', 
                        serverUrl: 'https://E5F18354D7B632FF2E865A0E7F4F1E2A.gr7.us-east-1.eks.amazonaws.com'
                    ]]) {
                        sh 'kubectl get all -n webapps'
                        sh 'sleep 60'
                    }
                }
            }
        }
        // stage('Deploy to EKS') {
        //     steps {
        //         script{
        //             withKubeCredentials(kubectlCredentials: [[caCertificate: '', clusterName: ' camp-cluster', contextName: '', credentialsId: 'k8-service-account-token', namespace: 'webapps', serverUrl: 'https://E5F18354D7B632FF2E865A0E7F4F1E2A.gr7.us-east-1.eks.amazonaws.com']]) {
        //                 sh 'kucel apply -f dss.yml'
        //                 sh 'sleep 60'
        //             }
        //         }
        //     }
        // }
    }

}
